import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useGetProfileByIdQuery } from './api/reptiloidAPI';

export default function Home() {
  const {data = {}, isLoading} = useGetProfileByIdQuery(1);
  
  if (isLoading) return <p>Loading...</p>
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {data.name}
        </h1>

        
      </main>

      <footer className={styles.footer}>
        
        
      </footer>
    </div>
  )
}
